namespace Migrator.Core;

using Microsoft.Data.SqlClient;
using Npgsql;

/// <summary>
/// Creates source-only tables in the target from the source schema ("mirror" mode).
///
/// Scope: columns (type, NOT NULL, identity), primary keys and foreign keys — enough for
/// the data copy to fill the tables 1:1 and for the orphan-row audit to have keys to
/// check. Defaults, indexes and check constraints are not copied; this is a data
/// migration aid, not a DDL port.
/// </summary>
public static class SchemaMirror
{
    public static async Task<bool> CreateMissingTablesAsync(
        SqlConnection sql, NpgsqlConnection pg,
        Dictionary<string, List<ColumnInfo>> sourceSchema,
        IReadOnlyList<string> missingTables,
        IEnumerable<string> existingTargetTables,
        IProgress<ProgressMessage> progress, CancellationToken ct = default)
    {
        progress.Report(new(ProgressKind.Step, "Mirroring missing tables", MessageCode.StepMirroring));
        progress.Report(new(ProgressKind.Info,
            $"{missingTables.Count} tables will be created from the source schema. " +
            "Defaults, indexes and check constraints are not copied.",
            MessageCode.InfoMirrorPlan, new object?[] { missingTables.Count }));

        var primaryKeys = await SchemaReader.ReadSqlServerPrimaryKeysAsync(sql, ct);

        // All DDL is generated before anything runs, so a single pass reports EVERY
        // unmappable column instead of failing on the first one.
        var ddl = new List<(string Table, string Sql)>();
        var fatal = false;
        foreach (var table in missingTables)
        {
            var lines = new List<string>();
            foreach (var column in sourceSchema[table])
            {
                // A rowversion is a counter the source server hands out and compares against
                // itself. Its bytes mean nothing anywhere else, and PostgreSQL has no way to
                // maintain one — mirrored as bytea NOT NULL with no default it becomes a
                // column nothing can ever fill, so every insert an application makes fails.
                // Skipped rather than made nullable: a column the ORM does not map is a
                // column that should not be in the target's shape at all.
                if (column.StoreType is "timestamp" or "rowversion")
                {
                    progress.Report(new(ProgressKind.Warning,
                        $"{table}.{column.Name}: rowversion is not mirrored — it is generated by the source server and has no meaning in the target.",
                        MessageCode.WarnMirrorSkippedRowVersion, new object?[] { table, column.Name }));
                    continue;
                }

                var type = MapType(column);
                if (type is null)
                {
                    progress.Report(new(ProgressKind.Error,
                        $"{table}.{column.Name}: source type '{column.StoreType}' has no PostgreSQL mapping — the table cannot be mirrored.",
                        MessageCode.ErrorMirrorUnsupportedType, new object?[] { table, column.Name, column.StoreType }));
                    fatal = true;
                    continue;
                }
                var identity = column.IsIdentity && type is "smallint" or "integer" or "bigint"
                    ? " GENERATED BY DEFAULT AS IDENTITY" : "";
                var notNull = column.IsNullable ? "" : " NOT NULL";
                lines.Add($"{TargetDatabase.Quote(column.Name)} {type}{identity}{notNull}");
            }
            if (primaryKeys.TryGetValue(table, out var pk))
                lines.Add($"PRIMARY KEY ({string.Join(", ", pk.Select(TargetDatabase.Quote))})");
            ddl.Add((table, $"CREATE TABLE {TargetDatabase.Quote(table)} (\n  {string.Join(",\n  ", lines)}\n)"));
        }
        if (fatal) return false;

        // One transaction for all tables: a failure halfway leaves nothing behind, so a
        // rerun does not trip over half a mirror.
        await using (var transaction = await pg.BeginTransactionAsync(ct))
        {
            foreach (var (table, createSql) in ddl)
            {
                await using var command = new NpgsqlCommand(createSql, pg, transaction) { CommandTimeout = 0 };
                await command.ExecuteNonQueryAsync(ct);
                progress.Report(new(ProgressKind.Info, $"  {table}: created",
                    MessageCode.InfoTableCreated, new object?[] { table }));
            }
            await transaction.CommitAsync(ct);
        }

        await CreateForeignKeysAsync(sql, pg, missingTables, existingTargetTables, progress, ct);
        return true;
    }

    /// <summary>
    /// Foreign keys are best-effort: each runs on its own, and one that fails (say, it
    /// references a unique constraint this tool does not mirror) becomes a warning, not a
    /// rollback — the orphan-row audit still covers whatever was created.
    /// </summary>
    private static async Task CreateForeignKeysAsync(
        SqlConnection sql, NpgsqlConnection pg,
        IReadOnlyList<string> missingTables, IEnumerable<string> existingTargetTables,
        IProgress<ProgressMessage> progress, CancellationToken ct)
    {
        var created = new HashSet<string>(missingTables, StringComparer.Ordinal);
        var present = new HashSet<string>(existingTargetTables, StringComparer.Ordinal);
        var count = 0;

        foreach (var fk in await SchemaReader.ReadSqlServerForeignKeysAsync(sql, ct))
        {
            if (!created.Contains(fk.ChildTable)) continue;
            if (!created.Contains(fk.ParentTable) && !present.Contains(fk.ParentTable))
            {
                progress.Report(new(ProgressKind.Warning,
                    $"Foreign key {fk.Name} skipped — parent table '{fk.ParentTable}' does not exist in the target.",
                    MessageCode.WarnMirrorFkSkipped, new object?[] { fk.Name, fk.ParentTable }));
                continue;
            }

            var childColumns = string.Join(", ", fk.Columns.Select(c => TargetDatabase.Quote(c.Child)));
            var parentColumns = string.Join(", ", fk.Columns.Select(c => TargetDatabase.Quote(c.Parent)));
            var onDelete = fk.DeleteAction switch
            {
                "CASCADE" => " ON DELETE CASCADE",
                "SET_NULL" => " ON DELETE SET NULL",
                "SET_DEFAULT" => " ON DELETE SET DEFAULT",
                _ => "",
            };
            try
            {
                await using var command = new NpgsqlCommand(
                    $"ALTER TABLE {TargetDatabase.Quote(fk.ChildTable)} ADD CONSTRAINT {TargetDatabase.Quote(fk.Name)} " +
                    $"FOREIGN KEY ({childColumns}) REFERENCES {TargetDatabase.Quote(fk.ParentTable)} ({parentColumns}){onDelete}",
                    pg) { CommandTimeout = 0 };
                await command.ExecuteNonQueryAsync(ct);
                count++;
            }
            catch (PostgresException ex)
            {
                progress.Report(new(ProgressKind.Warning,
                    $"Foreign key {fk.Name} could not be created: {ex.MessageText}",
                    MessageCode.WarnMirrorFkFailed, new object?[] { fk.Name, ex.MessageText }));
            }
        }

        if (count > 0)
            progress.Report(new(ProgressKind.Info, $"{count} foreign keys created.",
                MessageCode.InfoMirrorForeignKeys, new object?[] { count }));
    }

    /// <summary>
    /// SQL Server data type -> PostgreSQL column type; null = no safe mapping. Every type
    /// produced here must have a case in MigrationEngine.WriteValueAsync, or the copy that
    /// follows the mirror would fail on its own output.
    /// </summary>
    private static string? MapType(ColumnInfo column) => column.StoreType switch
    {
        "uniqueidentifier" => "uuid",
        "bit" => "boolean",
        "tinyint" or "smallint" => "smallint",
        "int" => "integer",
        "bigint" => "bigint",
        "decimal" or "numeric" => column.Precision is int p ? $"numeric({p},{column.Scale ?? 0})" : "numeric",
        "money" => "numeric(19,4)",
        "smallmoney" => "numeric(10,4)",
        "real" => "real",
        "float" => "double precision",
        "nvarchar" or "varchar" => column.MaxLength > 0 ? $"character varying({column.MaxLength})" : "text",
        "nchar" or "char" => column.MaxLength > 0 ? $"character({column.MaxLength})" : "text",
        "text" or "ntext" or "xml" => "text",
        // timestamp/rowversion are deliberately absent: they are skipped before they get
        // here, and leaving a mapping would let a future caller quietly recreate the
        // unfillable NOT NULL column this skip exists to prevent.
        "binary" or "varbinary" or "image" => "bytea",
        "datetime" or "datetime2" or "smalldatetime" => "timestamp without time zone",
        "datetimeoffset" => "timestamp with time zone",
        "date" => "date",
        "time" => "time without time zone",
        _ => null,
    };
}
